from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup

start_kb = ReplyKeyboardMarkup(resize_keyboard=True)
start_kb.add('ГЛАВНОЕ МЕНЮ')

menu_kb = InlineKeyboardMarkup(row_width=1)
m1 = InlineKeyboardButton('Группа VK', url='https://vk.com/promofartovogo')
m2 = InlineKeyboardButton('✅Гарантии✅', callback_data='guarantee')
m3 = InlineKeyboardButton('🔥Покупка🔥', callback_data='payment')
m4 = InlineKeyboardButton('ДОП. ИНФОРМАЦИЯℹ️', callback_data='dop_info')
m5 = InlineKeyboardButton('СВЯЗЬ С НАМИ', url='https://t.me/fedotovgr')
menu_kb.add(m1, m2, m3, m4, m5)

back_menu = InlineKeyboardMarkup(row_width=1)
back1 = InlineKeyboardButton('⏪ВЕРНУТЬСЯ', callback_data='back')
back_menu.add(back1)

pay_menu = InlineKeyboardMarkup(row_width=1)
ege = InlineKeyboardButton('ЕГЭ', callback_data='ege')
oge = InlineKeyboardButton('ОГЭ', callback_data='oge')
sochen = InlineKeyboardButton('Итоговое сочинение', callback_data='sochen')
sobes = InlineKeyboardButton('Итоговое собеседование', callback_data='sobes')
pay_menu.add(ege, oge, sochen, sobes)
take_results = InlineKeyboardMarkup(row_width=1)
kr1 = InlineKeyboardButton('Получить ответы', callback_data='otvet')
take_results.add(kr1)

ege_lessons_ikb = InlineKeyboardMarkup(row_width=1)
oge_lessons_ikb = InlineKeyboardMarkup(row_width=1)
l1 = InlineKeyboardButton('БАЗОВАЯ МАТЕМАТИКА', callback_data='postoplata')
l2 = InlineKeyboardButton('ПРОФИЛЬНАЯ МАТЕМАТИКА', callback_data='postoplata')
l3 = InlineKeyboardButton('ФИЗИКА', callback_data='postoplata')
l4 = InlineKeyboardButton('ОБЩЕСТВОЗНАНИЕ', callback_data='postoplata')
l5 = InlineKeyboardButton('ИСТОРИЯ', callback_data='postoplata')
l6 = InlineKeyboardButton('ХИМИЯ', callback_data='postoplata')
l7 = InlineKeyboardButton('БИОЛОГИЯ', callback_data='postoplata')
l8 = InlineKeyboardButton('ГЕОГРАФИЯ', callback_data='postoplata')
l9 = InlineKeyboardButton('ИНФОРМАТИКА', callback_data='postoplata')
l10 = InlineKeyboardButton('РУССКИЙ ЯЗЫК', callback_data='postoplata')
l11 = InlineKeyboardButton('ЛИТЕРАТУРА', callback_data='postoplata')
l12 = InlineKeyboardButton('АНГЛИЙСКИЙ ЯЗЫК', callback_data='postoplata')
l13 = InlineKeyboardButton('НЕМЕЦКИЙ ЯЗЫК', callback_data='postoplata')
l14 = InlineKeyboardButton('ФРАНЦУЗСКИЙ ЯЗЫК', callback_data='postoplata')
l15 = InlineKeyboardButton('ИСПАНСКИЙ ЯЗЫК', callback_data='postoplata')
l16 = InlineKeyboardButton('КИТАЙСКИЙ ЯЗЫК', callback_data='postoplata')
l17 = InlineKeyboardButton('⏪ВЕРНУТЬСЯ', callback_data='payment')
l18 = InlineKeyboardButton('КИТАЙСКИЙ ЯЗЫК', callback_data='postoplata')
ege_lessons_ikb.add(l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17)
oge_lessons_ikb.add(l18, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17)
start_fsm = ReplyKeyboardMarkup(resize_keyboard=True).add(KeyboardButton('/take_answers'))
